## Artificial Neural Network

In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
X = dataset.iloc[:, 3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y = dataset.iloc[:, 13].values
y

array([1, 0, 1, ..., 1, 1, 0])

Criando as variáveis categóricas para os países e os gêneros

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

É preciso informar que sao variáveis categóricas, ou seja, 0,1,2 nao indica um peso e sim uma  categoria

( criar as variáveis dummy ) - criar tem colunas no início para representar os países - tipo 0 - 1 0 0 ,1 - 0 1 0 e o 2 - 0 0 1 - a biblioteca adiciona estas variáveis antes das outras e remove o campo característico dos países

In [8]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:] # remove a primeira coluna pq nao preciso
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ...,
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [9]:
X[0,:]

array([  0.00000000e+00,   0.00000000e+00,   6.19000000e+02,
         0.00000000e+00,   4.20000000e+01,   2.00000000e+00,
         0.00000000e+00,   1.00000000e+00,   1.00000000e+00,
         1.00000000e+00,   1.01348880e+05])

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train

array([[  0.00000000e+00,   1.00000000e+00,   6.67000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.63830640e+05],
       [  1.00000000e+00,   0.00000000e+00,   4.27000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   5.70980000e+04],
       [  0.00000000e+00,   0.00000000e+00,   5.35000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.85630760e+05],
       ...,
       [  0.00000000e+00,   0.00000000e+00,   7.38000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.81429870e+05],
       [  0.00000000e+00,   1.00000000e+00,   5.90000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.48750160e+05],
       [  1.00000000e+00,   0.00000000e+00,   6.23000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.18855260e+05]])

In [13]:
X_test

array([[  1.00000000e+00,   0.00000000e+00,   5.97000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.92852670e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.23000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.28702100e+05],
       [  0.00000000e+00,   1.00000000e+00,   7.06000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   7.57322500e+04],
       ...,
       [  0.00000000e+00,   1.00000000e+00,   5.78000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.41533190e+05],
       [  1.00000000e+00,   0.00000000e+00,   6.50000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.12764800e+04],
       [  1.00000000e+00,   0.00000000e+00,   5.73000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.92950600e+05]])

In [14]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [17]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [18]:
# Initialising the ANN
classifier = Sequential()

OBS- #ReLU
A função ReLU é a unidade linear rectificada. É definida como:

f(x) = max (0, x)

Não ativa todos os neurônios ao mesmo tempo. O que isto significa ? Se você olhar para a função ReLU e a entrada for negativa, ela será convertida em zero e o neurônio não será ativado. Isso significa que, ao mesmo tempo, apenas alguns neurônios são ativados, tornando a rede esparsa e eficiente e fácil para a computação.

In [19]:
# Adding the input layer and the first hidden layer
#init = 'uniform' indica que os pesos serão iniciados com uma distribuição uniforme
# tipo de função de ativaçao de cada neurônio - activation = 'relu'
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

/Users/arnaldojr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.

In [20]:
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/Users/arnaldojr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`

In [21]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

/Users/arnaldojr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`

No caso de uma camada de saída com 3 categorias deve-se mundar a dimensão de output e a função de ativação seria a softmax

In [22]:
classifier

optimizer = 'adam'-> indica que o tipo de gradiente descendente estocástico é o 'adam'

loss = 'binary_crossentropy' -> indica que a função de erro será a função logaritmica para saída binária

metrics = ['accuracy'] -> é o modo como ele atualiza os pesos da rede neural

In [23]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [24]:
classifier

batch_size = 10 -> indica que após 10 observações que os pesos serão atualizados

nb_epoch = 100 -> todos os dados passarão 100 vezes pela rede no treinamento

In [25]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/Users/arnaldojr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

Epoch 1/100
8000/8000 [==============================] - 3s 399us/step - loss: 0.4921 - acc: 0.7965
Epoch 2/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4197 - acc: 0.8196
Epoch 3/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4120 - acc: 0.8292
Epoch 4/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4075 - acc: 0.8314
Epoch 5/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4046 - acc: 0.8341
Epoch 6/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.4030 - acc: 0.8345
Epoch 7/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4019 - acc: 0.8336
Epoch 8/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.4016 - acc: 0.8364
Epoch 9/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4007 - acc: 0.8350
Epoch 10/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.4002 - acc: 0.8362
Epoch 11/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.3996 - acc: 0.8356
Epoch 12/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3991 - acc: 0.8356
Epoch 13/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3986 - acc: 0.8370
Epoch 14/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3983 - acc: 0.8359
Epoch 15/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3974 - acc: 0.8366
Epoch 16/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3971 - acc: 0.8360
Epoch 17/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.3969 - acc: 0.8364
Epoch 18/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3973 - acc: 0.8360
Epoch 19/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3962 - acc: 0.8360
Epoch 20/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3962 - acc: 0.8367
Epoch 21/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3960 - acc: 0.8360
Epoch 22/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3961 - acc: 0.8359
Epoch 23/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3958 - acc: 0.8367
Epoch 24/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3957 - acc: 0.8371
Epoch 25/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.3954 - acc: 0.8367
Epoch 26/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3953 - acc: 0.8356
Epoch 27/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3954 - acc: 0.8362
Epoch 28/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.3950 - acc: 0.8365
Epoch 29/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3951 - acc: 0.8369
Epoch 30/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3948 - acc: 0.8379
Epoch 31/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3943 - acc: 0.8370
Epoch 32/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3944 - acc: 0.8385
Epoch 33/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3939 - acc: 0.8369
Epoch 34/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3943 - acc: 0.8367
Epoch 35/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3943 - acc: 0.8367
Epoch 36/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3942 - acc: 0.8360
Epoch 37/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.3940 - acc: 0.8361
Epoch 38/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3936 - acc: 0.8374
Epoch 39/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3935 - acc: 0.8365
Epoch 40/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3935 - acc: 0.8376
Epoch 41/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3932 - acc: 0.8365
Epoch 42/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3929 - acc: 0.8366
Epoch 43/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3926 - acc: 0.8374
Epoch 44/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3919 - acc: 0.8375
Epoch 45/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3910 - acc: 0.8384
Epoch 46/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3892 - acc: 0.8390
Epoch 47/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.3873 - acc: 0.8380
Epoch 48/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3847 - acc: 0.8382
Epoch 49/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3818 - acc: 0.8401 1s
Epoch 50/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.3788 - acc: 0.8406
Epoch 51/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3763 - acc: 0.8407
Epoch 52/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.3748 - acc: 0.8400
Epoch 53/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3723 - acc: 0.8391
Epoch 54/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.3712 - acc: 0.8404
Epoch 55/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3698 - acc: 0.8380
Epoch 56/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3686 - acc: 0.8426
Epoch 57/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.3677 - acc: 0.8380
Epoch 58/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3661 - acc: 0.8364
Epoch 59/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3645 - acc: 0.8364
Epoch 60/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3622 - acc: 0.8427
Epoch 61/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3611 - acc: 0.8442
Epoch 62/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3594 - acc: 0.8477
Epoch 63/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3582 - acc: 0.8517
Epoch 64/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3554 - acc: 0.8545
Epoch 65/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.3553 - acc: 0.8574
Epoch 66/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.3539 - acc: 0.8556
Epoch 67/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3525 - acc: 0.8571
Epoch 68/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3526 - acc: 0.8590
Epoch 69/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3508 - acc: 0.8589
Epoch 70/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3508 - acc: 0.8605
Epoch 71/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.3496 - acc: 0.8585
Epoch 72/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.3494 - acc: 0.8601
Epoch 73/100
8000/8000 [==============================] - 2s 268us/step - loss: 0.3484 - acc: 0.8594
Epoch 74/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3482 - acc: 0.8600
Epoch 75/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.3477 - acc: 0.8591
Epoch 76/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3476 - acc: 0.8616
Epoch 77/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3466 - acc: 0.8626
Epoch 78/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.3463 - acc: 0.8614
Epoch 79/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3459 - acc: 0.8639
Epoch 80/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3450 - acc: 0.8620
Epoch 81/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3452 - acc: 0.8629
Epoch 82/100

8000/8000 [==============================] - 1s 179us/step - loss: 0.3443 - acc: 0.8615
Epoch 83/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3443 - acc: 0.8611
Epoch 84/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3439 - acc: 0.8614
Epoch 85/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3431 - acc: 0.8620
Epoch 86/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3431 - acc: 0.8621
Epoch 87/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3444 - acc: 0.8621
Epoch 88/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3433 - acc: 0.8637
Epoch 89/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.3424 - acc: 0.8632
Epoch 90/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3422 - acc: 0.8621
Epoch 91/100
8000/8000 [==============================] - 2s 216us/step - loss: 0.3428 - acc: 0.8622
Epoch 92/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3418 - acc: 0.8611
Epoch 93/100
8000/8000 [==============================] - 2s 288us/step - loss: 0.3414 - acc: 0.8624
Epoch 94/100
8000/8000 [==============================] - 2s 271us/step - loss: 0.3421 - acc: 0.8611
Epoch 95/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.3413 - acc: 0.8621
Epoch 96/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.3419 - acc: 0.8619
Epoch 97/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.3411 - acc: 0.8627
Epoch 98/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.3403 - acc: 0.8625
Epoch 99/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.3405 - acc: 0.8644
Epoch 100/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3406 - acc: 0.8625

In [26]:
y_pred = classifier.predict(X_test)

In [27]:
y_pred

array([[ 0.23972832],
       [ 0.35465074],
       [ 0.15516272],
       ...,
       [ 0.16775909],
       [ 0.17318138],
       [ 0.23809685]], dtype=float32)

In [28]:
#probabilidada de 23% de deixar o banco
y_pred[0]

array([ 0.23972832], dtype=float32)

In [29]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], dtype=bool)

In [30]:
#indica que o cliente zero nao deixou o banco
y_pred[0]

array([False], dtype=bool)

In [32]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1488,  107],
       [ 175,  230]])

In [33]:
#Acurácia do modelo 
(1488+230)/2000

0.859